DEPS = vector.h
obj = logger.obj main.obj video.obj input.obj utils.obj gameobjs.obj 
bin = hello.exe

CC = wpp386
CFLAGS = -zq -4s -er -hw
LD = wlink

$(bin): $(obj)
	$(LD) name $@ file *.obj

.c.obj:
	$(CC) -fo=$@ $(CFLAGS) $<

clean: .symbolic
	del *.obj
	del $(bin) 
